config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  namespace :api, defaults: {format: :json} do
    resources :edibles, only: [:show, :index]
    resources :reviews, except: :new
    resources :lists, except: :new
    resources :list_items, except: :new
    resources :users, only: [:index, :create, :show]
    resource :session, only: [:create, :destroy, :show]
  end
end

app/models/edible.rb
class Edible < ActiveRecord::Base
  validates :name, :description, :category, :image_url, presence: true

  has_many :list_items
  has_many :lists, through: :list_items, source: :list
  has_many :reviews
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, :user_id, presence: true
  validates :title, length: {maximum: 24} 
  validates :can_delete, inclusion: { in: [true, false] }
  validates :title, uniqueness: { scope: :user_id, message: "List couldn't be created. List name is a duplicate."}

  belongs_to :user
  has_many :list_items, dependent: :destroy
  has_many :edibles, through: :list_items
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  validates :list_id, :edible_id, presence: true
  validates :edible_id, uniqueness: { scope: :list_id, message: "You've already added this item." }

  belongs_to :list
  belongs_to :edible
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :user_id, :edible_id, :title, :body, presence: true
  validates :edible_id, uniqueness: { scope: :user_id, message: "You've already reviewed this item." }

  belongs_to :user
  belongs_to :edible
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :password_digest, presence: true
  validates :session_token, :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :lists, dependent: :destroy
  has_many :list_items, through: :lists
  has_many :reviews, dependent: :destroy

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.is_password?(password)
    user
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/api/edibles_controller.rb
class Api::EdiblesController < ApplicationController
  def index
    @edibles = Edible.all
    render :index
  end

  def show
    @edible = Edible.find(params[:id])
    render :show
  end

  def update
    @edible = Edible.find(params[:id])
    @edible.update(edible_params)
    render :show
  end

  def edible_params
    params.require(:edible).permit(:name, :description, :category, :image_url, list_ids: [])
  end
end

app/controllers/api/list_items_controller.rb
class Api::ListItemsController < ApplicationController
  def create
    @list_item = ListItem.new(list_item_params)
    if @list_item.save
      render json: @list_item
    else
      render json: "Failed to add item to your list."
    end
  end

  def index
    @list_items = ListItem.all
    render :index
  end

  def show
    @list_item = ListItem.find(params[:id])
    render :show
  end

  def edit
  end

  def update
    @list_item = ListItem.find(params[:id])
    if @list_item.update(list_item_params)
      render json: @list_item
    else
      render json: "Error"
    end
  end

  def destroy
    @list_item = ListItem.find(params[:id])
    @list_item.destroy
    render json: @list_item
  end

  def list_item_params
    params.require(:list_item).permit(:list_id, :edible_id, :rating, :review, :date_eaten, :created_at)
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController
  def index
    @lists = List.where("user_id = ?", current_user.id)
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id;
    if @list.save
      render :show
    else
      render json: @list.errors.full_messages, status: 422
    end
  end

  def edit
    @list = List.find(params[:id])
    render :edit
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      render :show
    else
      render json: @list.errors.full_messages
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    render :show
  end

  def list_params
    params.require(:list).permit(:title, :user_id, :can_delete)
  end
end

app/controllers/api/reviews_controller.rb
class Api::ReviewsController < ApplicationController

  def index
    @reviews = Review.all
    render :index
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id

    if @review.save
      render json: @review
    else
      render json: "Failed to create review."
    end
  end

  def show
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    render :edit
  end

  def update
    if @review.update(review_params)
      render json: @review
    else
      render json: "Failed to update review."
    end
  end

  def review_params
    params.require(:review).permit(:user_id, :edible_id, :title, :body)
  end
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < ApplicationController

  def show

    if current_user
      @user = current_user
      render "api/users/show"
    else
      render json: {}
    end
  end

  def create
    @user = User.find_by_credentials(
      params[:email],
      params[:password]
    )

    if @user.nil?
      render json: ["Wrong email/password combo!"], status: 401
    else
      sign_in!(@user)
      render "api/users/show"
    end
  end

  def destroy
    sign_out!
    render json: {}
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in!(@user)
      List.create!(title: "Want to Try", user_id: @user.id, can_delete: false)
      List.create!(title: "Eaten", user_id: @user.id, can_delete: false)
      render :show
    else
      render json: "Login failed."
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  protected

  def user_params
    self.params.require(:user).permit(:email, :name, :password, :image_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil if self.session[:session_token].nil?
    @current_user ||= User.find_by(session_token: self.session[:session_token])
  end

  def sign_in!(user)
    @current_user = user
    @current_user.reset_session_token!
    self.session[:session_token] = @current_user.session_token
  end

  def sign_out!
    current_user.try(:reset_session_token!)
    self.session[:session_token] = nil
  end

  def ensure_user_logged_in
    unless current_user
      render json: ["Nope."]
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user
      login_user(user)
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    logout_user
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user(@user)
      List.create!(title: "Want to Try", user_id: current_user.id, can_delete: false)
      List.create!(title: "Eaten", user_id: current_user.id, can_delete: false)
      redirect_to root_url
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/api/edibles_helper.rb
module Api::EdiblesHelper
end

app/helpers/api/list_items_helper.rb
module Api::ListItemsHelper
end

app/helpers/api/reviews_helper.rb
module Api::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>goodeats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato" />
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,100' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<script>
  window.goodeatsAssets = {
    logo: "<%= asset_path("Dollarphotoclub_72620313.jpg") %>",
    auth_photo_new_session: "<%= asset_path("burger_background.png") %>",
    auth_photo_new_user: "<%= asset_path("kiwi.jpg") %>" 
  }
</script>

<%= yield %>

  <%= javascript_include_tag 'application' %>

</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sign Up</title>
  </head>

  <header class="auth-header">
    <nav class="auth-header-nav group">

      <h1 class="auth-header-logo">
        <a href="#">goodeats</a>
      </h1>

      <ul class="auth-header-list group">
        <li>
          <h5 class="auth-header-five">Already a member?</h5>
        </li>
        <li>
          <a class="auth-alternate-link" href="../session/new">Sign in</a>
        </li>

      </ul>

    </nav>
  </header>

  <body class="auth-body">
    <section class="auth-form">
      <form action="<%= users_url %>" method="POST">
        <p class="auth-form-description">
          Sign up to see what your friends are eating, get food recommendations,
      and join the world’s most devoted community of eaters.
        </p>

        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <fieldset class="auth-form-fieldset">
          <label>Name
            <input type="text" name="user[name]" placeholder="Name" value="">
          </label>

          <label>Email
            <input type="text" name="user[email]" placeholder="Email" value="">
          </label>

          <label>Password
            <input type="password" name="user[password]" placeholder="Password" value="">
          </label>

          <button class="auth-form-button">Sign up</button>
        </fieldset>

        <p class="auth-form-agreement">
          By clicking “Sign up” I agree to the Goodeats Terms of Service and confirm that I am at least 13 years old.
        </p>
      </form>
    </section>

    <footer class="auth-footer">
      <p class="auth-footer-copy">© 2016 Goodeats Inc</p>
      <img class="auth-footer-banner"
           src="http://www.calabriamillbury.com/images/italian.jpg"/>
    </footer>

  </body>
</html>